### PR TITLE
Separate route for Contact Us

### PR DESCRIPTION
**Pull request by Pranav-Rustagi**
### All Submissions:

- [x] Have you followed the guidelines stated in [README.md](https://github.com/IshaanAdarsh/ezmail/tree/main#how-to-contribute) file?
- [x] Have you checked to ensure there aren't any other open [Pull Requests](https://github.com/IshaanAdarsh/ezmail/pulls) for the desired changed?

### Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### **After** these steps, you're ready to open a pull request.

    a. Give a descriptive title to your PR.

    b. Describe your changes.

    c. Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).

### CODE REVIEW

**Comment by Pranav-Rustagi** [comment]
@IshaanAdarsh Please verify whether I understand it correct. 
1. The contact us section is to appear in the end of "About us" page
2. Navigation bar should have Contact Us link as well

**Comment by IshaanAdarsh** [comment]
> @IshaanAdarsh Please verify whether I understand it correct.
> 
> 1. The contact us section is to appear in the end of "About us" page
> 2. Navigation bar should have Contact Us link as well

Yes the 1st part is correct but the 2nd should not happen as it looks very clustered

**Comment by Pranav-Rustagi** [comment]
@IshaanAdarsh Please verify the changes

**Comment by IshaanAdarsh** [comment]
Great

**Comment by Pranav-Rustagi** [comment]
@IshaanAdarsh Could you please add the "hacktoberfest-accepted" label as well

**Pull request merged**
