### PR TITLE
Issue #124

### LINKED ISSUE #124: Improvement: Enhance UI of About Us Section on the Website
## Description
The current UI of the "About Us" section on our website could benefit from some improvements to enhance user experience and visual appeal. This issue is created to track and address the necessary enhancements in the UI design of this section.

## Current UI Pain Points
- [ ] Lack of visual hierarchy.
- [ ] Text and images not well-aligned.
- [ ] Limited use of engaging elements.
- [ ] Inconsistencies in color scheme and typography.

## Proposed Changes
- [ ] Establish a clear visual hierarchy to guide users through the content.
- [ ] Ensure proper alignment of text and images for a cleaner look.
- [ ] Introduce visually engaging elements to make the section more appealing.
- [ ] Harmonize the color scheme and typography for consistency.

## Additional Information
Feel free to provide additional context, ideas, or suggestions that could contribute to the improvement of the "About Us" section. Screenshots, if available, would be helpful for a better understanding of the current state.

## Acceptance Criteria
- [ ] The UI changes should enhance the overall aesthetics and usability.
- [ ] The improvements should be consistent with the overall design language of the website.

Screenshot 2023-12-13 at 5 29 31 PM

### PR DESCRIPTION
**Pull request by mendacium-a11y**
### All Submissions:

- [x] Have you followed the guidelines stated in [README.md](https://github.com/IshaanAdarsh/ezmail/tree/main#how-to-contribute) file?
- [x] Have you checked to ensure there aren't any other open [Pull Requests](https://github.com/IshaanAdarsh/ezmail/pulls) for the desired changed?

### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

fixed #124 
- fixed positioning of the elements
- added margin between heading and their text
- chnaged the starting color of the gradient for the headings to make it more visible
Screenshot 2023-12-22 at 12-56-24 Screenshot

### CODE REVIEW

**Comment by IshaanAdarsh** [comment]
@mendacium-a11y, there is a lot of margin, could you reduce that.
Also i was thinking of making the about us into 4 grid boxes, and styling them. i ma open to suggestions.
simple center aligned text doesn't seem very appealing/

**Comment by mendacium-a11y** [comment]
> there is a lot of margin, could you reduce that
between each section or between the heading and the text or both?

**Comment by mendacium-a11y** [comment]
> Also i was thinking of making the about us into 4 grid boxes, and styling them. i ma open to suggestions. simple center aligned text doesn't seem very appealing

i can try that, see how it looks, then go on from there if anything else needs to be done

**Comment by IshaanAdarsh** [comment]
> > there is a lot of margin, could you reduce that
> 
> between each section or between the heading and the text or both?

between each section. its too much

**Comment by mendacium-a11y** [comment]
image
image

i don't think the gird layout looks very good

**Comment by IshaanAdarsh** [comment]
Yup, could you try something, because the center aligned doesn't look good either. If there is nother then we can stick with what you proposed

**Comment by mendacium-a11y** [comment]
Screenshot 2023-12-22 at 16-40-38 Screenshot
i've made the content a bit concise, added padding to the sides, better?

**Comment by IshaanAdarsh** [comment]
> Screenshot 2023-12-22 at 16-40-38 Screenshot i've made the content a bit concise, added padding to the sides, better?

great

**Review by IshaanAdarsh — APPROVED** [review]
Sorry, there is a lot of padding and it looks very unpleasant. Could you reduce the padding @mendacium-a11y

**Comment by IshaanAdarsh** [comment]
@mendacium-a11y, i have a design element in mid for this. If you want you can work on some other issue. Sorry for the inconvenience

**Comment by mendacium-a11y** [comment]
yeah yeah no worries

**Pull request merged**
