### PR TITLE
made features section responsive and updated readme

### PR DESCRIPTION
**Pull request by ani-netizen**
Hey @IshaanAdarsh 

I have completed the task and made one fix in readme that I noticed. Kindly review it and if there are any changes do let me know. And if everything is fine kindly accept the request. Also the file with : in its name is deleted kindly add it again from your side
Thank you

### CODE REVIEW

**Comment by IshaanAdarsh** [comment]
@ani-netizen could you link the issue this PR is linked too.

**Comment by ani-netizen** [comment]
> @ani-netizen could you link the issue this PR is linked too.

image

not getting option to link

**Comment by IshaanAdarsh** [comment]
#26

**Review by IshaanAdarsh — APPROVED** [review]
Incredible work @ani-netizen !!
Looking forward to more awesome contributions from you 🚀
Consider starring the repo for better reach

**Pull request merged**
