### PR TITLE
Enhance UI of About Us Section on the website

### PR DESCRIPTION
**Pull request by ayann07**
### All Submissions:

- [yes ] Have you followed the guidelines stated in [README.md](https://github.com/IshaanAdarsh/ezmail/tree/main#how-to-contribute) file?
- [ yes] Have you checked to ensure there aren't any other open [Pull Requests](https://github.com/IshaanAdarsh/ezmail/pulls) for the desired changed?

    a. Give a descriptive title to your PR.
       Issue number #124  is solved 
    b. Describe your changes.
      I have enhanced UI of About Us Section on the website.
    c. Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).

### CODE REVIEW

**Comment by IshaanAdarsh** [comment]
@ayann07 the top margin is a lot also the letter spacing needs to be corrected. But rest all good. make these changes

Screenshot 2023-12-23 at 10 26 33 AM

**Comment by ayann07** [comment]
Okay , I will make these changes .

**Comment by ayann07** [comment]
I have now done the changes, kindly check.

**Review by IshaanAdarsh — APPROVED** [review]
Great @ayann07.

**Pull request merged**
