### PR TITLE
created signin and login pages using mongoDB as a database

### PR DESCRIPTION
**Pull request by Albert-2**
### All Submissions:

- [x] Have you followed the guidelines stated in [README.md](https://github.com/IshaanAdarsh/ezmail/tree/main#how-to-contribute) file?
- [x] Have you checked to ensure there aren't any other open [Pull Requests](https://github.com/IshaanAdarsh/ezmail/pulls) for the desired changed?

### Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

### **After** these steps, you're ready to open a pull request.

    a. Give a descriptive title to your PR.
     
    b. Describe your changes.

    c. Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).

### CODE REVIEW

**Comment by Albert-2** [comment]
hey @IshaanAdarsh 
i have created sign and login using mongoDB as a database 
if you need any further help than please let me know 
thank you...!:)

**Comment by Albert-2** [comment]
hey @IshaanAdarsh 
sorry but how do i solve this check my node and npm versions are v18.16.1 and 9.8.0 respectively 
and i am also able to build this project 
image
THANK YOU ...!!:)

**Comment by IshaanAdarsh** [comment]
@Albert-2 Don't worry about the performance fail. we are working on it. 
I wanted a small change in the nav bar. The login option should not be the only thing in the navbar. We want a small profile picture beside the chosen language and if the user chooses to login we will give them an option to them. The website should function the same if the user doesn't feel like logging in. We will add special features for the users as time goes on.

**Comment by Albert-2** [comment]
correct me if i am wrong 
you want this (to professor ,about n all) options to be visible irrespective of if the user is logged in or not
and the small profile icon beside the chosen language which will redirect user to log in page and if the user is new then he will redirect to the sign in page

**Comment by IshaanAdarsh** [comment]
Also @Albert-2 don’t worry about the backend of the login page. We will handle that on our end. Just make the front-end as good as possible

**Pull request closed without merging**
