### PR TITLE
Suitable changes made to hamburger menu

### LINKED ISSUE #45: Improve Hamburger Menu UI to Match Site Design
**Issue Description:**
The current design of the hamburger menu on the website does not align with the overall design aesthetics of the site. It appears inconsistent and affects the user experience. This issue is raised to enhance the UI of the hamburger menu to match the site's design language seamlessly.

**Steps to Reproduce:**
1. Visit the website.
2. Observe the hamburger menu's design and appearance.
3. Compare it to the site's overall design.

**Expected Behavior:**
The hamburger menu should be visually consistent with the site's design, ensuring a cohesive and pleasing user experience.

**Actual Behavior:**
The current hamburger menu design appears inconsistent with the site's overall design.

**Additional Information:**
A cohesive and visually appealing UI enhances the overall user experience, making navigation more intuitive and engaging.

**Proposed Changes:**
1. Analyze the website's design language.
2. Redesign the hamburger menu to match the overall design aesthetics.
3. Ensure that the new design maintains responsiveness for different devices.

https://github.com/IshaanAdarsh/ezmail/assets/93966956/e5d7e536-610e-44eb-8d7c-afabfe4c2d3d

### PR DESCRIPTION
**Pull request by shrutiiigupta**
### All Submissions:

- [ ] Have you followed the guidelines stated in [README.md](https://github.com/IshaanAdarsh/ezmail/tree/main#how-to-contribute) file?
Yes
- [ ] Have you checked to ensure there aren't any other open [Pull Requests](https://github.com/IshaanAdarsh/ezmail/pulls) for the desired changed?
Yes

### Type of change
- [ ] Changed UI for better visuals.

Made changes to hamburger menu UI to match website design

`closes #45`

### CODE REVIEW

**Comment by IshaanAdarsh** [comment]
@shrutiiigupta, could you change the hover effect of the menu too, that is what is most needed. Because the minimal change to then text is not looking great. maybe a purple box with white text when hovering over the each menu item or something better if you can think of it.

**Comment by shrutiiigupta** [comment]
Okayy, I'll do it

**Comment by shrutiiigupta** [comment]
I made the changes..

**Review by IshaanAdarsh — APPROVED** [review]
Incredible work @shrutiiigupta !!
Looking forward to more awesome contributions from you 🚀
Consider starring the repo for better reach

**Pull request merged**
