### PR TITLE
Login

### PR DESCRIPTION
**Pull request by Albert-2**
### All Submissions:

- [x] Have you followed the guidelines stated in [README.md](https://github.com/IshaanAdarsh/ezmail/tree/main#how-to-contribute) file?
- [x] Have you checked to ensure there aren't any other open [Pull Requests](https://github.com/IshaanAdarsh/ezmail/pulls) for the desired changed?

### Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

### **After** these steps, you're ready to open a pull request.

    a. Give a descriptive title to your PR.

    b. Describe your changes.

    c. Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).

### CODE REVIEW

**Comment by Albert-2** [comment]
hey @IshaanAdarsh ...!
i have made changes according to what you said
let me know if you need any help or changes
THANK YOU....!!:)

**Comment by IshaanAdarsh** [comment]
@Albert-2 we want to host the bakend on postgres. could you just keep the forntend and remove all the backend files

**Comment by Albert-2** [comment]
do you want me to delete server folder only or server folder plus all the changes i have done like http request and all

**Comment by IshaanAdarsh** [comment]
Just the server folder will be enough i guess. You can test out the deployment on your side and afterwards just PR and we will check it out

**Comment by IshaanAdarsh** [comment]
@Albert-2 amazing work.

**Comment by Albert-2** [comment]
Thanks if you have any work/issue which can be solved by MERN
please let me know....!!

**Comment by IshaanAdarsh** [comment]
> Thanks if you have any work/issue which can be solved by MERN please let me know....!!

Sure will keep it in mind

**Pull request merged**
